name: slidable_line_chart
description: A line chart plugin that responds to user sliding. Supports reverse and custom slide precision.
repository: https://github.com/moxiaov587/slidable_line_chart
version: 1.0.2

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
